apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindtrack-deployment
  labels:
    app: mindtrack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindtrack
  template:
    metadata:
      labels:
        app: mindtrack
    spec:
      containers:
        - name: mindtrack
          image: ${IMAGE_URI}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000